### ISSUE TITLE
dependency on winrt means no python 3.10+

### ISSUE THREAD

**Issue by markjreed** [dany74q/ctap-keyring-device#7]
Since Microsoft has stopped maintaining winrt and there is no version for Python 3.10, ctap should switch to using the community-maintained winsdk module instead.

**Comment by dany74q** [comment]
Thanks !

Dealt w/ it here - https://github.com/dany74q/ctap-keyring-device/pull/9
I'll need to pin the previous version in gimme-aws-creds (the biggest user of this library) before creating a new tag with the changes, as the bump to fido2 v1.0.0 contains some breaking changes.

**Comment by markjreed** [comment]
g-a-c was what led me here, since we can’t install it on windows without pinning Python below 3.10.  Obviously that needs to be updated to work with the newer Fido, but any chance of a version with just the winsdk fix and not the updated dependencies?
